graph TD
	BepInEx(BepInEx starts) -->|prior preloader patchers| DeliStart

    DeliStart[Deli starts] --> FindMods
	FindMods[Find mods] --> MountMods
	MountMods["Mount mods to virtual file system (VFS)"] --> ParseMods
	ParseMods[Parse mods] --> OrderMods
	OrderMods[Order mods] --> PatcherStage
	PatcherStage["Patcher stage (sequential; before plugins)"] -->|subsequent preloader patchers| Chainloader

	Chainloader[BepInEx chainloader starts] --> DeliContinue
	DeliContinue[Deli continues] --> SetupStage
	SetupStage["Setup stage (sequential; before game)"] --> RuntimeStage
	RuntimeStage["Runtime stage (sequential; during game)"] --> VersionChecking
	VersionChecking[Version checking] --> DeliEnd
	DeliEnd(Deli finished)
