[book]
authors = ["Ash"]
language = "en"
multilingual = false
src = "src"
title = "The Book of Masonry"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/H3VR-Modding/Mason.git"
edit-url-template = "https://github.com/H3VR-Modding/Mason/edit/main/docs/{path}"
