on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build -c Release

      - name: Pack NuGet
        run: dotnet pack -c Release --no-build Mason

      - name: Pack Thunderstore
        run: ./pack.sh Mason/nupkg/Thunderstore.zip

      - name: Publish Standlone
        run: |
          dotnet publish -c Release --no-build Mason
          pushd Mason/bin/Release/net5.0/publish
          zip -9r ../../../../nupkg/Standlone.zip .
          popd

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Mason
          path: |
            Mason/nupkg/Standalone.zip
            Mason/nupkg/Thunderstore.zip
            Mason/nupkg/*.nupkg
